x = input("enter the first number ")
y = input("enter the second number ")
z = float(x) + float(y)
print(x , end = " ")
print(" + " , end = " ")
print(y , end= " ")
print("= " , end = " ")
print(f"{z: ,}")
print("Round form : " , end = " ")
print(round(z))
